#!/bin/bash

print_help() {
    echo "Usage: pyfunk [options] <script.py> <function_name>"
    echo "Options:"
    echo "  -h           Show this help message and exit"
    echo "  -c           Include comments in the output"
    exit 0
}

# Default settings
include_comments=false

# Parse options
while getopts ":hc" opt; do
    case ${opt} in
        h)
            print_help
            ;;
        c)
            include_comments=true
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
    esac
done
shift $((OPTIND -1))

# Check if the correct number of arguments is provided
if [ "$#" -ne 2 ]; then
    print_help
    exit 1
fi

# Assign arguments to variables
SCRIPT="$1"
FUNCTION_NAME="$2"

# Check if the file exists
if [ ! -f "$SCRIPT" ]; then
    echo "File $SCRIPT does not exist."
    exit 1
fi

# Use awk to extract the function definition and its content
if $include_comments; then
    awk -v fname="$FUNCTION_NAME" '
        $0 ~ "^def " fname "\\(" {flag=1}
        flag && $0 ~ /^def / && $0 !~ "^def " fname "\\(" {flag=0}
        flag {print}
    ' "$SCRIPT"
else
    awk -v fname="$FUNCTION_NAME" '
        $0 ~ "^def " fname "\\(" {flag=1}
        flag && $0 ~ /^def / && $0 !~ "^def " fname "\\(" {flag=0}
        flag && $1 !~ "^#" {print}
    ' "$SCRIPT"
fi
